# Generated by Django 5.2.5 on 2025-09-01 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/время операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='directories.status', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashflows', to='directories.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Запись ДДС',
                'verbose_name_plural': 'Записи ДДС',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='cashflow_ca_created_d57e52_idx'), models.Index(fields=['status'], name='cashflow_ca_status__e32625_idx'), models.Index(fields=['subcategory'], name='cashflow_ca_subcate_490e61_idx')],
            },
        ),
    ]
